title: Victor Silva
email: victor.silva@grinply.com
description: "What i cannot build, i don't understand"
url: "https://victorfts.com"

github_username:  victorl2

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

header_pages:
  - _pages/about.md

include:
    - _pages

minima:
  skin: dark

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
